GET https://localhost:5084/task1
###
GET https://localhost:5084/task2
###
GET https://localhost:5084/task3
###
GET https://localhost:5084/task5
###
GET https://localhost:5084/task6
###
GET https://localhost:5084/task7
###
GET https://localhost:5084/task8
###
GET https://localhost:5084/task9
###
GET https://localhost:5084/task10
###
GET https://localhost:5084/task11
###
POST https://centrala.ag3nts.org/report

{
  "task" : "dokumenty",
  "apikey" : "...",
  "answer" : {
    "2024-11-12_report-00-sektor_C4.txt" : "Godzina 22:43, jednostka organiczna, północne skrzydło fabryki, Aleksander Ragowski, skan biometryczny, dział kontroli, patrol, nauczyciel języka angielskiego, Szkoła Podstawowa nr 9, Grudziądz, kreatywne metody nauczania, zaangażowanie w społeczność szkolną, automatyzacja, rząd robotów, krytyk reżimu, tajne spotkania, zagrożenia edukacyjne, algorytmy, sztuczna inteligencja, aresztowanie, ucieczka, miejsce pobytu nieznane, obrzeża miast, strefy niedostępne, patrol automatyczny, aktywność, programowanie, Java, psychika, opozycja, zabezpieczenia systemów rządowych, wróg reżimu, zgłoszenie miejsca pobytu.",
    "2024-11-12_report-01-sektor_A1.txt" : "Godzina 03:26, alarm wykrycia, ruch organiczny, lokalna zwierzyna leśna, fałszywy alarm, obszar bezpieczny, trasa patrolu, Sektor C, fabryka, testowanie nowoczesnej broni, wzmocnione pomieszczenie, zaawansowane systemy bezpieczeństwa, ochroną przed wyciekiem materiałów niebezpiecznych, kontrolowane eksplozje, stanowiska testowe, grube ściany, osłony przeciwodłamkowe, broń o dużej mocy, automatyczne systemy monitorujące, analiza danych, mocno ograniczony dostęp, uprawnieni technicy, inżynierowie, specjalne identyfikatory, odzież ochronna, ściśle tajne, archiwizacja testów, raportowanie, wyżsi przełożeni.",
    "2024-11-12_report-02-sektor_A3.txt" : "Godzina 02:15, obszar patrolu nocnego, sektor D, magazyn, materiały i komponenty, produkcja podzespołów mechanicznych, przebudowa fabryki, nadwyżki materiałów i urządzeń, części zamienne do robotów, surowce, obsługa techniczna, bezpieczeństwo zasobów, monitoring, alarmy, nieautoryzowany dostęp, strefa produkcyjna, strefa laboratoryjna, elastyczny układ, funkcja magazynowa, zaawansowane projekty.",
    "2024-11-12_report-03-sektor_A3.txt" : "Godzina 01:30, patrole nocne, sektor A, fabryka, montaż zaawansowanych robotów przemysłowych, jednostki wojskowe, strefy montażu, linie produkcyjne, roboty przemysłowe, komponenty, strefy wojskowe, izolacja, zabezpieczenia, ochrona technologii, kontroli jakości, testy robotów, tajność konstrukcji, inżynierowie, operatorzy, kontrole bezpieczeństwa, sztuczna inteligencja, optymalizacja pracy, technicy, zaawansowane egzoszkielety, sektor A monitoring, systemy biometryczne, najtajniejsze projekty, punkt strategiczny, techniczny postęp, autonomia robotów, adaptacyjność robotów.",
    "2024-11-12_report-04-sektor_B2.txt" : "Patrol, zachodni teren, Sektor C, fabryka, testowanie nowoczesnej broni, systemy bezpieczeństwa, wyciek materiałów niebezpiecznych, niekontrolowane eksplozje, stanowiska testowe, grube ściany, osłony przeciwodłamkowe, automatyczne systemy monitorujące, technicy, inżynierowie, identyfikatory, odzież ochronna, ściśle tajne, archiwizacja, raportowanie, przełożeni.",
    "2024-11-12_report-05-sektor_C1.txt" : "04:02, Sektor C, fabryka, zaawansowane systemy bezpieczeństwa, nowoczesna broń, testowanie broni, detektory ruchu, sensor dźwiękowy, monitorowanie, technicy, inżynierowie, identyfikatory, odzież ochronna, materiały niebezpieczne, eksplozje, tajne prace, automatyczne systemy monitorujące, raportowanie, wyżsi przełożeni, ściany przeciwodłamkowe, stanowiska testowe.",
    "2024-11-12_report-06-sektor_C2.txt" : "22:50, sektor północno-zachodni, sektor C, testowanie nowoczesnej broni, zaawansowane systemy bezpieczeństwa, stanowiska testowe, grube ściany, osłony przeciwodłamkowe, automatyczne systemy monitorujące, uprawnieni technicy, inżynierowie, specjalne identyfikatory, odzież ochronna, tajne prace, archiwizacja testów, raportowanie, wyższe przełożone.",
    "2024-11-12_report-07-sektor_C4.txt" : "Barbara Zawadzka, czujniki dźwięku, ultradźwiękowy sygnał, nadajnik, las, dział śledczy, obszar zabezpieczony, patrol zakończony, Sektor C4, odciski palców, JavaScript, fabryka, testowanie nowoczesnej broni, zaawansowane systemy bezpieczeństwa, materiały niebezpieczne, niekontrolowane eksplozje, stanowiska testowe, ściany i osłony przeciwodłamkowe, automatyczne systemy monitorujące, uprawnieni technicy, inżynierowie, specjalne identyfikatory, odzież ochronna, ściśle tajne prace, archiwizacja testów, raportowanie do przełożonych.",
    "2024-11-12_report-08-sektor_A1.txt" : "Godzina 01:00, Monitoring obszaru patrolowego, brak ruchu, Sektor C, fabryka, nowoczesna broń, zaawansowane systemy bezpieczeństwa, ochrona przed materiałami niebezpiecznymi, ochrona przed eksplozjami, stanowiska testowe, grube ściany, osłony przeciwodłamkowe, automatyczne systemy monitorujące, analiza danych, uprawnieni technicy, inżynierowie, specjalne identyfikatory, odzież ochronna, tajne prace, archiwizacja testów, raportowanie do przełożonych.",
    "2024-11-12_report-09-sektor_C2.txt" : "Patrol, godzina 03:45, zachodnie peryferia, brak anomalii, Sektor C, fabryka, testowanie nowoczesnej broni, zaawansowane systemy bezpieczeństwa, materiały niebezpieczne, niekontrolowane eksplozje, stanowiska testowe, ściany przeciwodłamkowe, broń o dużej mocy, automatyczne systemy monitorujące, technicy, inżynierowie, uprawnieni pracownicy, identyfikatory, odzież ochronna, tajne prace, archiwizacja testów, raportowanie, wyżsi przełożeni."
  }
}
###
GET https://localhost:5084/task12
###
GET https://localhost:5084/task13