GET https://localhost:5084/task1
###
GET https://localhost:5084/task2
###
GET https://localhost:5084/task3
###
GET https://localhost:5084/task5
###
GET https://localhost:5084/task6
###
GET https://localhost:5084/task7
###
GET https://localhost:5084/task8
###
GET https://localhost:5084/task9
###
GET https://localhost:5084/task10
###